In [1]:
import numpy as np

x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [2]:
print(x.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
y = np.arange(18).reshape(2, 3, 3)
print(y)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [4]:
y = np.arange(18).reshape(3, 3, 2)
print(y)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
