In [1]:
import numpy as np
mat_a = np.matrix([0, 3, 5, 5, 5, 2]).reshape(2, 3)
print(mat_a)

[[0 3 5]
 [5 5 2]]


In [2]:
mat_b = np.matrix([3, 4, 3, -2, 4, -2]).reshape(3, 2)
print(mat_b)

[[ 3  4]
 [ 3 -2]
 [ 4 -2]]


In [3]:
print(mat_a * mat_b)

[[ 29 -16]
 [ 38   6]]


In [4]:
product = np.matmul(mat_a, mat_b)
print(product)

[[ 29 -16]
 [ 38   6]]


In [5]:
print(mat_a @ mat_b)

[[ 29 -16]
 [ 38   6]]
