In [1]:
import numpy as np

x = np.arange(4).reshape(2, 2)
print(x)

[[0 1]
 [2 3]]


In [2]:
y = np.arange(4, 8).reshape(2, 2)
print(y)

[[4 5]
 [6 7]]


In [3]:
z = np.hstack((x, y))
print(z)

[[0 1 4 5]
 [2 3 6 7]]


In [4]:
print(x.shape)
print(z.shape)

(2, 2)
(2, 4)


In [5]:
w = np.concatenate((x,y), axis = 1)
print(w)

[[0 1 4 5]
 [2 3 6 7]]


In [6]:
y = np.arange(8).reshape(4, 2)
print(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [7]:
z = np.vstack((x, y))
print(z)

[[0 1]
 [2 3]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]


In [8]:
print(y.shape)
print(z.shape)

(4, 2)
(6, 2)


In [9]:
w = np.concatenate((x,y), axis = 0)
print(w)

[[0 1]
 [2 3]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]
